config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'users#index'
	post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
	post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
	resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
	has_many :following_user, through: :follower, source: :followed # 自分[が]フォローしている人
	has_many :follower_user, through: :followed, source: :follower # 自分[を]フォローしている人

	# ユーザーをフォローする
	def follow(user_id)
		follower.create(followed_id: user_id)
	end

	# ユーザーのフォローを外す
	def unfollow(user_id)
		follower.find_by(followed_id: user_id).destroy
	end

	# フォローしていればtrueを返す
	def following?(user)
		following_user.include?(user)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow
		current_user.follow(params[:id])
		redirect_to root_path
	end

	def unfollow
		current_user.unfollow(params[:id])
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRelationship</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <% unless user_signed_in? %>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% else %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <p><%= link_to "マイページへ", user_path(current_user) %></p>
  <h2>ユーザー一覧画面</h2>
  <% User.all.where.not(id: current_user.id).each do |user| %>
    <p>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <%= link_to "show", user_path(user) %>
    </p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2>ユーザー詳細ページ</h2>
<p><%= "id: #{@user.id}" %></p>
<p><%= "フォロー数: #{@user.follower.count}" %></p>
<p><%= "フォロワー数: #{@user.followed.count}" %></p>
<% unless @user == current_user %>
  <% if current_user.following?(@user) %>
    <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
  <% else %>
    <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
  <% end %>
<% end %>
<p></p>

<h3>フォロー一覧</h3>
  <% @user.following_user.where.not(id: current_user.id).each do |user| %>
    <p>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <%= link_to "show", user_path(user) %>
    </p>
  <% end %>
<h3>フォロワー一覧</h3>
  <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
    <p>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <%= link_to "show", user_path(user) %>
    </p>
  <% end %>